### ISSUE TITLE
Update mediator coordination protocol

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#1823] opened 2020-05-13 19:15 UTC
See https://github.com/hyperledger/aries-rfcs/blob/0b75a4c59d7e33cf0d0e4f292d2425402de94d43/features/0211-route-coordination/README.md

- Protocol URI: `https://didcomm.org/coordinatemediation/1.0/`

**Comment by llorllale** [comment] 2020-05-13 19:19
duplicate of #1448

**Closed by llorllale** 2020-05-13 19:19 UTC
