### ISSUE TITLE
Writing peer DID to a store

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#105] opened 2019-08-13 20:19 UTC
Peer DID documents should be stored in the wallet. The Wallet will contain an injectable storage.Store. Peer DID documents should be passed to the Wallet such that its storage is handled by the Store implementation.

This issue is under epic #97

**Comment by llorllale** [comment] 2019-08-14 18:14
@talwinder50 closed as duplicate of #47

**Closed by llorllale** 2019-08-14 18:14 UTC
Labels: enhancement
