### ISSUE TITLE
Mobile Agent build issue

### ISSUE THREAD

**Issue by llbartekll** [hyperledger/aries-framework-go#2339] opened 2020-11-20 12:25 UTC
Hi, 
I have no experience with `go` so maybe it is something obvious

**What I'm trying to do**

I am trying to build mobile library as described here: https://github.com/hyperledger/aries-framework-go/tree/master/cmd/aries-agent-mobile 

**Expected result**

successfully build mobile library

**Actual result**

I am getting error after calling `make all` 

```  
 Installing dependencies              

gomobile init -v
make: gomobile: No such file or directory
make:  [dependencies] Error 1
```

**Comment by soluchok** [comment] 2020-11-20 13:37
@llbartekll Could please install gomobile. Just execute `go get golang.org/x/mobile/cmd/gomobile` command in your terminal.

**Comment by llbartekll** [comment] 2020-11-22 10:40
@soluchok thank you for help. It was 1st of the reasons. later I had to export path so:
`go get golang.org/x/mobile/cmd/gomobile`
`export PATH=$PATH:$HOME/go/bin   `
finally android bindings were created but I am still not able to make ios-bindings. I am getting error:
```
...
github.com/hyperledger/aries-framework-go/pkg/crypto/tinkcrypto/primitive/composite/keyio
github.com/hyperledger/aries-framework-go/pkg/crypto/tinkcrypto/primitive/composite/ecdh
github.com/hyperledger/aries-framework-go/pkg/crypto/tinkcrypto
gomobile: darwin-arm64: go build -tags ios -v -ldflags -s -w -buildmode=c-archive -o /var/folders/7d/64g9s7d53ks0s2pj3rmrp0d40000gn/T/gomobile-work-357594089/AriesAgent-arm64.a ./gobind failed: exit status 1

make: *** [bindings-ios] Error 1
```

**Comment by soluchok** [comment] 2020-11-28 09:01
@llbartekll the fix was merged. Could you please confirm that the issue is resolved?

**Comment by llbartekll** [comment] 2020-12-01 12:59
@soluchok yes, It works, thank you :)

**Comment by soluchok** [comment] 2020-12-01 13:01
@llbartekll I will close this issue. Thanks for participating.

**Closed by soluchok** 2020-12-01 13:01 UTC
