### ISSUE TITLE
ci: include test files in linter

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#84] opened 2019-08-09 20:17 UTC
This should fail:
https://github.com/hyperledger/aries-framework-go/pull/66/files#diff-7de7681f01cd73c279bb10b7466c2953R127

**Comment by llorllale** [comment] 2019-08-09 20:26
I could not reproduce this by moving around closing brackets in the `master` branch

**Comment by troyronda** [comment] 2019-08-09 20:31
@llorllale Are you saying this is happening only on CircleCI not locally?

**Comment by llorllale** [comment] 2019-08-09 20:52
@troyronda no. I just pulled @talwinder50's [branch](https://github.com/talwinder50/aries-framework-go/tree/issue-48) and `make lint` runs with no issues

**Comment by rolsonquadras** [comment] 2019-08-09 21:12
@troyronda I think it didn't fail as test files are ignored from linter check - https://github.com/hyperledger/aries-framework-go/blob/master/.golangci.yml#L15

**Comment by troyronda** [comment] 2019-08-09 23:28
We shouldn’t exclude test files. I’ll update description.

**Closed** 2019-08-12 14:38 UTC
Labels: bug
