### ISSUE TITLE
DID Exchange Inbound Message Events (service)

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#198] opened 2019-09-03 16:56 UTC
Created issue based on discussion in https://wiki.hyperledger.org/display/ARIES/2019-09-03+Framework+Go+Weekly+Planning.

Framework should provide the ability to register events on inbound protocol messages. 

When protocol service [receives](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/didcomm/dispatcher/dispatcher.go#L11) the message, the service should invoke the events registered by the [clients](https://github.com/hyperledger/aries-framework-go/tree/master/pkg/client).

**Comment by llorllale** [comment] 2019-09-03 21:05
This sounds like either it's a duplicate of #140 or depends on it

**Comment by fqutishat** [comment] 2019-09-09 14:57
duplicate of #140

**Comment by llorllale** [comment] 2019-09-10 13:57
Rough proposal, as discussed:

* expose identifiers for the different states ("Invited", "Requested", "Responded", "Completed")
* add `AddListener(string, <-chan dispatcher.DIDCommMsg) chan<- bool` to `didexchange.Service`

Usage:

```go
package user

func foo () {
    svc := /* get handle to didexchange.Service */
    incoming := make(<-chan dispatcher.DIDCommMsg)
    outgoing := svc.AddListener(didexchange.Invited, incoming)
    select {
    case msg <- incoming:
        // verify incoming invitation
        outgoing <- true    // aprove
    case <- time.After(100 * time.Second):
        // abort
    }
}
```

**Comment by sudeshrshetty** [comment] 2019-09-10 14:59
instead of `incoming := make(<-chan dispatcher.DIDCommMsg)`
we can create channel of struct type which includes 

- ID : for correlation
- Error: in case of some failure
- dispatcher.DIDCommMsg: actual message

**Comment by llorllale** [comment] 2019-09-10 15:21
Sounds good.

Note: `ID` would be for correlating *events* to the callback.

**Closed** 2019-09-17 20:38 UTC
Labels: enhancement
