### ISSUE TITLE
Resolving peer DID from storage

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#106] opened 2019-08-13 20:21 UTC
We need a did:peer method resolver to be plugged by default into didresolver.DIDResolver. This resolver needs to resolve peer DID documents from the storage.Store.

This issue is derived from #97

**Comment by talwinder50** [comment] 2019-08-14 15:22
@llorllale how this is different than https://github.com/hyperledger/aries-framework-go/issues/79

**Comment by llorllale** [comment] 2019-08-14 18:14
@talwinder50 closed as duplicate of #79

**Closed by llorllale** 2019-08-14 18:14 UTC
Labels: enhancement
